In [58]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [59]:
data = pd.read_csv("cars93.csv")

datax = data[["MPG.city", "MPG.highway", "Horsepower"]]
datax["MPG.city"] = (datax["MPG.city"] - datax["MPG.city"].min()) / (datax["MPG.city"].max() - datax["MPG.city"].min())
datax["MPG.highway"] = (datax["MPG.highway"] - datax["MPG.highway"].min()) / (datax["MPG.highway"].max() - datax["MPG.highway"].min())
datax["Horsepower"] = (datax["Horsepower"] - datax["Horsepower"].min()) / (datax["Horsepower"].max() - datax["Horsepower"].min())
datax = datax.to_numpy()
datay = data["Price"].to_numpy()
x_train, x_test, y_train, y_test = train_test_split(datax, datay, random_state=1488, test_size=0.25)

print(x_test.shape)
print(y_test.shape)

(24, 3)
(24,)


/tmp/ipykernel_13832/3136766221.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datax["MPG.city"] = (datax["MPG.city"] - datax["MPG.city"].min()) / (datax["MPG.city"].max() - datax["MPG.city"].min())
/tmp/ipykernel_13832/3136766221.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datax["MPG.highway"] = (datax["MPG.highway"] - datax["MPG.highway"].min()) / (datax["MPG.highway"].max() - datax["MPG.highway"].min())
/tmp/ipykernel_13832/3136766221.py:6: SettingWithCopyWarning: 
A value is trying to be se

In [64]:
def predict(x, weights, b):
    return np.dot(x, weights)+b

def do_linear_regression(x_train, y_train):
    b = np.random.rand()
    weights = np.array([np.random.rand() for i in range(x_train.shape[1])])
    for _ in range(25):
        for i in range (x_train.shape[0]):
            pred = predict(x_train[i], weights, b)
            loss =(pred - y_train[i])**2
            
            dw = 2 * x_train[i] * (pred - y_train[i])
            db = 2 * (pred - y_train[i])
            
            weights -= 0.01 * dw
            b -= 0.01 * db
        print(loss)
    return b, weights

In [61]:
bias, weights = do_linear_regression(x_train, y_train)

45.26715686427887
71.16146346698035
65.31096330238552
55.78256134250451
47.37244521613484
40.46694936674328
34.84595058741966
30.25911989718722
26.498882135910918
23.400671551599185
20.834748377546234
18.698645820298086
16.911165641360775
15.40772002127557
14.136729130282328
13.056832045248594
12.134722837317426
11.34346756997351
10.661191804420556
10.07005407529985
9.555440535667824
9.105331033844422
8.709798390875052
8.360611444054665
8.05091915413646


In [62]:
predict(x_test, weights, bias)

array([14.30971987, 12.11630432, 18.63747808, 17.65554716, 15.50380131,
       18.71132136, 14.66633952, 21.25401831,  8.696143  , 24.33213549,
       22.19310317, 23.3994074 ,  9.71660427, 19.34151715, 19.36195869,
       27.52478415, 12.59646083, 35.83227363, 22.61183406, 18.50474099,
       20.56072979, 25.69581726, 23.22109757, 15.64024657])

In [65]:
y_test

array([13.4, 10.3, 19.7, 10. , 14.1, 31.9, 11.4, 18.4,  7.4, 16.3, 17.7,
       26.3,  9.8, 20.2, 15.8, 19.3, 10. , 47.9, 19.1, 17.5, 19.8, 28. ,
       24.4, 11.1])

In [67]:
weights

array([-6.80415212, -5.34929486, 25.18586282])